/**
 * Demo data for the customer-app HOME screen: the five top stores (Mobile, Mobile Part, Accessories,
 * Electronics, Repellents & Fresheners), their category tab strips, hero banners, mosaic tiles and icons.
 * Placeholder artwork lives in ./home-demo-assets (generated by generate.py).
 *
 *   node src/database/seeds/home-demo.js            add (idempotent: replaces the previous demo rows)
 *   node src/database/seeds/home-demo.js --clear    remove ONLY the demo rows
 *
 * Inside Docker:  docker compose exec api node src/database/seeds/home-demo.js
 *
 * Tagging: every demo theme is named 'DEMO · …'; every demo tab belongs to one of the five Dealker store keys
 * (nothing else uses those keys). --clear deletes those and nulls the store icons. Requires migration 191.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const { query, pool } = await import('../../config/database.js')
const { redis } = await import('../../config/redis.js')
const { UPLOAD_DIR, PUBLIC_BASE } = await import('../../modules/uploads/local-uploads.routes.js')

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ASSETS = path.join(HERE, 'home-demo-assets')
const OUT_DIR = path.join(UPLOAD_DIR, 'demo-home')
const STORES = ['mobile', 'mobile_part', 'accessories', 'electronics', 'repellents']
const clear = process.argv.includes('--clear')

const url = (name) => `${PUBLIC_BASE}/demo-home/${name}.png`

const YELLOW = '#F7DC4E'
const YELLOW_SOFT = '#FBE979'

const TABS = {
  mobile: [
    ['all', 'All', 'tab-all'], ['ramadan', 'Ramadan', 'tab-ramadan'], ['fashion', 'Fashion', 'tab-fashion'],
    ['beauty', 'Beauty', 'tab-beauty'], ['health', 'Health', 'tab-health'], ['home', 'Home', 'tab-home'],
  ],
  mobile_part: [['all', 'All', 'tab-all'], ['screens', 'Screens', 'tab-screens'], ['batteries', 'Batteries', 'tab-batteries'], ['chargers', 'Chargers', 'tab-chargers']],
  accessories: [['all', 'All', 'tab-all'], ['earbuds', 'Earbuds', 'tab-earbuds'], ['cables', 'Cables', 'tab-cables'], ['cases', 'Cases', 'tab-cases']],
  electronics: [['all', 'All', 'tab-all'], ['laptops', 'Laptops', 'tab-laptops'], ['tv', 'TV', 'tab-tv'], ['audio', 'Audio', 'tab-audio']],
  repellents: [['all', 'All', 'tab-all'], ['repellents', 'Repellents', 'tab-repellents'], ['fresheners', 'Fresheners', 'tab-fresheners'], ['cleaning', 'Cleaning', 'tab-cleaning']],
}
const STORE_ICON = {
  mobile: 'store-mobile', mobile_part: 'store-mobile-part', accessories: 'store-accessories',
  electronics: 'store-electronics', repellents: 'store-repellents',
}
const HERO = {
  mobile: ['banner-mobiles', 'banner-accessories'], mobile_part: ['banner-parts', 'banner-mobiles'],
  accessories: ['banner-accessories', 'banner-mobiles'], electronics: ['banner-mobiles', 'banner-parts'],
  repellents: ['banner-accessories', 'banner-parts'],
}
const HINTS = {
  mobile: ['Festive Vibes', 'iPhone 15', 'Samsung 5G', 'Redmi Note'],
  mobile_part: ['Screen replacement', 'Battery', 'Charging port', 'Back panel'],
  accessories: ['Earbuds', 'Power bank', 'Fast charger', 'Phone case'],
  electronics: ['Laptop', 'Smart TV', 'Bluetooth speaker', 'Smart watch'],
  repellents: ['Mosquito repellent', 'Room freshener', 'Floor cleaner', 'Air freshener'],
}

const themeData = (store) => ({
  meta: { seasonLabel: 'DEMO', statusBarBrightness: 'dark' },
  sections: {
    topBar: { textColor: '#111111', backgroundColor: YELLOW },
    feeStrip: { visible: true, imageUrl: null },
    bankOffers: { visible: false, bannerImageUrls: [] },
    searchZone: { waveColor: YELLOW, searchHints: HINTS[store], backgroundColor: YELLOW_SOFT, promoBoxImageUrl: url('promo-repellents') },
    storeSelector: { activeChipColor: '#FFFFFF', backgroundColor: YELLOW },
    seasonalMosaic: {
      heroTile: { title: 'DEAL ZONE', gradient: ['#FFA43A', '#F57C00'], badgeText: 'BUY 1\nGET 2', badgeGradient: ['#111111', '#111111'] },
      miniTiles: [
        { title: 'Home Furnishing', gradient: ['#FFF4DB', '#FFF4DB'], imageUrl: url('tile-furnishing') },
        { title: 'Gardening & More', gradient: ['#FFF4DB', '#FFF4DB'], imageUrl: url('tile-gardening') },
        { title: 'Home Decor', gradient: ['#FFF4DB', '#FFF4DB'], imageUrl: url('tile-decor') },
        { title: 'Home Improvement', gradient: ['#FFF4DB', '#FFF4DB'], imageUrl: url('tile-improvement') },
      ],
      containerColor: YELLOW_SOFT,
    },
    bannerAnimation: { lottieUrl: null, containerColor: YELLOW_SOFT, backgroundGradient: [YELLOW_SOFT, YELLOW] },
  },
})

const sectionRows = (store) => [
  ['promo_carousel', { banner_source: 'custom', images: HERO[store].map(url), height: 200 }],
  ['fee_strip', { visible: true, image_url: null, pill_style: 'soft', accent_color: '#111111' }],
  ['seasonal_mosaic', {
    layout_variant: 'hero_plus_four', hero_ratio: '16:10', tile_radius: 16, container_color: YELLOW_SOFT,
    hero_tile: { title: 'DEAL ZONE', gradient: ['#FFA43A', '#F57C00'], badge_text: 'BUY 1\nGET 2', badge_gradient: ['#111111', '#111111'], image_url: url('deal-zone') },
    mini_tiles: [
      { title: 'Home Furnishing', gradient: ['#FFF4DB', '#FFF4DB'], image_url: url('tile-furnishing') },
      { title: 'Gardening & More', gradient: ['#FFF4DB', '#FFF4DB'], image_url: url('tile-gardening') },
      { title: 'Home Decor', gradient: ['#FFF4DB', '#FFF4DB'], image_url: url('tile-decor') },
      { title: 'Home Improvement', gradient: ['#FFF4DB', '#FFF4DB'], image_url: url('tile-improvement') },
    ],
  }],
]

async function removeDemo(client) {
  await client.query(`DELETE FROM app_themes WHERE name LIKE 'DEMO · %'`)
  await client.query(`DELETE FROM theme_tabs WHERE store_key = ANY($1)`, [STORES])
  await client.query(`UPDATE storefront_stores SET icon_url = NULL, updated_at = NOW() WHERE store_key = ANY($1)`, [STORES])
}

async function flushCaches() {
  try {
    let cursor = '0'
    do {
      const [next, keys] = await redis.scan(cursor, 'MATCH', 'bakaloo:*', 'COUNT', 200)
      cursor = next
      if (keys.length) await redis.del(...keys)
    } while (cursor !== '0')
  } catch (e) {
    console.warn('cache flush skipped:', e.message)
  }
}

const client = await pool.connect()
try {
  await client.query('BEGIN')
  await removeDemo(client)

  if (!clear) {
    fs.mkdirSync(OUT_DIR, { recursive: true })
    for (const f of fs.readdirSync(ASSETS).filter((n) => n.endsWith('.png'))) fs.copyFileSync(path.join(ASSETS, f), path.join(OUT_DIR, f))

    for (const store of STORES) {
      await client.query(`UPDATE storefront_stores SET icon_url = $2, updated_at = NOW() WHERE store_key = $1`, [store, url(STORE_ICON[store])])
      let order = 0
      for (const [key, label, icon] of TABS[store]) {
        const tab = await client.query(
          `INSERT INTO theme_tabs (store_key, key, label, image_url, sort_order, status, is_default)
           VALUES ($1,$2,$3,$4,$5,'active',$6) RETURNING id`,
          [store, key, label, url(icon), order, key === 'all'],
        )
        const tabId = tab.rows[0].id
        await client.query(
          `INSERT INTO app_themes (name, is_active, theme_data, tab_key, tab_label, tab_icon_url, tab_order, status, tab_id)
           VALUES ($1, false, $2, $3, $4, $5, $6, 'active', $7)`,
          [`DEMO · ${store} · ${label}`, JSON.stringify(themeData(store)), key, label, url(icon), order, tabId],
        )
        let s = 0
        for (const [type, config] of sectionRows(store)) {
          await client.query(
            `INSERT INTO section_manifests (tab_id, section_type, sort_order, visible, config) VALUES ($1,$2,$3,true,$4)`,
            [tabId, type, s++, JSON.stringify(config)],
          )
        }
        order++
      }
    }
  }
  await client.query('COMMIT')
  await flushCaches()
  console.log(clear ? 'Demo home data removed.' : `Demo home data added for: ${STORES.join(', ')}`)
} catch (e) {
  await client.query('ROLLBACK')
  console.error('Seed failed:', e.message)
  process.exitCode = 1
} finally {
  client.release()
  await pool.end()
  try { await redis.quit() } catch { /* ignore */ }
}
